### ISSUE TITLE
Uncaught TypeError: img.toPng is not a function

### ISSUE THREAD

**Issue by IliassTAHIRI** [simon123h/latex-image-paste#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [latex-image-paste](https://github.com/simon123h/latex-image-paste) package 0.3.0

### Stack Trace

Uncaught TypeError: img.toPng is not a function

```
At C:\Users\i.tahiri\.atom\packages\latex-image-paste\lib\main.coffee:47

TypeError: img.toPng is not a function
    at Object.handle_cp (/packages/latex-image-paste/lib/main.coffee:47:21)
    at /packages/latex-image-paste/lib/main.coffee:38:10
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.29.0/resources/app/src/command-registry.js:360:24)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.29.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
  9x -4:08.1.0 core:select-right (input.hidden-input)
  3x -4:06.0 core:backspace (input.hidden-input)
     -4:05.4.0 intentions:highlight (input.hidden-input)
     -4:05.0 core:save (input.hidden-input)
     -3:48.7.0 intentions:highlight (input.hidden-input)
     -3:47.3.0 markdown-writer:insert-new-line (input.hidden-input)
     -3:47.3.0 autocomplete-plus:confirm (input.hidden-input)
     -3:39.7.0 core:backspace (input.hidden-input)
     -3:39.6.0 intentions:highlight (input.hidden-input)
     -3:39.4.0 core:save (input.hidden-input)
     -0:11.7.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:11.7.0 editor:newline (input.hidden-input)
     -0:11.5.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:11.5.0 editor:newline (input.hidden-input)
     -0:11.2.0 intentions:highlight (input.hidden-input)
     -0:10.9.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.8.4 
autocomplete-python 1.10.10 
busy-signal 1.4.3 
dictionary 0.5.0 
git-plus 8.0.1 
intentions 1.1.5 
language-latex 1.1.1 
latex 0.50.0 
latex-image-paste 0.3.0 
latex-plus 0.9.1 
latexer 0.3.0 
latextools 0.8.5 
linter 2.2.0 
linter-chktex 1.3.1 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.7.1 
markdown-writer 2.9.0 
minimap 4.29.8 
pdf-view 0.71.0 
project-manager 3.3.6 
tool-bar 1.1.7 
tool-bar-markdown-writer 0.4.0 
wordcount 3.0.0 
Zen 0.18.0 
```

**Comment by simon123h** [comment]
Thanks for reporting!
The issue should be fixed with commit a2bac97d5785ba8e09b3dc0c29efcd3b32f1cc74.
Feel free to reopen if the problem persists.
